spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    root: INFO
    org:
      springframework:
        vault: DEBUG
        cloud.vault: DEBUG
